# Generated by Django 3.2 on 2021-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
